wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.16.6
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1714286030.0
    t:
      1:
      - 55
      - 86
      - 95
      - 105
      2:
      - 55
      - 86
      - 95
      - 105
      3:
      - 2
      - 23
      4: 3.11.8
      5: 0.16.6
      8:
      - 1
      - 4
      - 5
      9:
        2: langchain
      13: darwin-arm64
